name = "YBdecoder"
uuid = "e30badd9-2fbf-431b-a8d1-d58eb7114bec"
authors = ["Thomas Van Himbeeck <62086517+tvanhimbeeck@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
