name = "YBdecoder"
uuid = "e30badd9-2fbf-431b-a8d1-d58eb7114bec"
version = "1.0.0-DEV"
authors = ["Thomas Van Himbeeck <62086517+tvanhimbeeck@users.noreply.github.com> and contributors"]

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
ArgCheck = "2.5.0"
Distributions = "0.25.123"
Plots = "1.41.4"
SparseArrays = "1.12.0"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
